### ISSUE TITLE
BF4 gets 500 error while calling payments API

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2314]
## Description
```

{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'lock_timeout': 30, 'identifier': 159274100111000101}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-11-04 01:57:11.038213",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 58, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:47881/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x5409D2B144a450C459A86c6352898Ef759EdE198. Expected 2..: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>InternalServerError: Transfer expired.<br> &nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:222762:31)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:47797:5)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:47371:13)<br> &nbsp; &nbsp;at /lc/index.js:47340:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:47391:12)<br> &nbsp; &nbsp;at next (/lc/index.js:47331:10)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:47793:12)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:47371:13)<br> &nbsp; &nbsp;at /lc/index.js:47340:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:47391:12)</pre>\n</body>\n</html>\n"
}
```

stack trace:

```
"Traceback (most recent call last):\n  
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    
return_val = self._run(*args, **kwargs)\n  
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 58, in _run\n    
f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\n

scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:47881/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x5409D2B144a450C459A86c6352898Ef759EdE198
```

**scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching**

`http://127.0.0.1:47881/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x5409D2B144a450C459A86c6352898Ef759EdE198`

from: 0, to: 3, amount: 1_000_000_000_000_000, lock_timeout: 30

```
- parallel:
          name: "Make 100 transfers from 0 to 2, 3 and 5 in parallel"
          tasks:
            - serial:
                name: "Make 100 transfers from 0 to 2"
                repeat: 100
                tasks:
                  - transfer: {from: 0, to: 2, amount: 1_000_000_000_000_000, lock_timeout: 30}
            - serial:
                name: "Make 100 transfers from 0 to 3"
                repeat: 100
                tasks:
                  - transfer: {from: 0, to: 3, amount: 1_000_000_000_000_000, lock_timeout: 30} **fails here**
            - serial:
                name: "Make 100 transfers from 0 to 5"
                repeat: 100
                tasks:
                  - transfer: {from: 0, to: 5, amount: 1_000_000_000_000_000, lock_timeout: 30}
```     

[scenario-player-run_bf4_multi_payments_same_node_2020-11-04T01:39:53.log](https://github.com/raiden-network/light-client/files/5487714/scenario-player-run_bf4_multi_payments_same_node_2020-11-04T01.39.53.log)

node0 and node3 logs:
The node logs are empty and dont really reveal much about the internal server error of the the raiden node.
[bf4_node0_node3_04thNov2020.tar.gz](https://github.com/raiden-network/light-client/files/5487716/bf4_node0_node3_04thNov2020.tar.gz)

## Acceptance criteria
- 

## Tasks
- [ ]
