### ISSUE TITLE
BF7 gets InternalServerError another transaction with same nonce in the queue.

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2318]
## Actual Result
```
{
  "task": "<OpenChannelTask: {'from': 1, 'to': 2, 'total_deposit': 1000000000000000000}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-11-05 02:10:24.277478",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 58, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:52275/api/v1/channels. Expected 2..: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>InternalServerError: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.<br> &nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:222762:31)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:47797:5)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:47371:13)<br> &nbsp; &nbsp;at /lc/index.js:47340:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:47391:12)<br> &nbsp; &nbsp;at next (/lc/index.js:47331:10)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:47793:12)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:47371:13)<br> &nbsp; &nbsp;at /lc/index.js:47340:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:47391:12)</pre>\n</body>\n</html>\n"
}
```

Exception 

```
 "Traceback (most recent call last):\n  
 File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    
 return_val = self._run(*args, **kwargs)\n  
 File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 58, in _run\n    
 f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\n
 ```
 scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:52275/api/v1/channels

**Internal Server Error**

```
<!DOCTYPE html>\n
<html lang=\"en\">\n
	<head>\n<meta charset=\"utf-8\">\n
		<title>Error</title>\n
	</head>\n
	<body>\n<pre>
		InternalServerError: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.<br> 
		&nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:222762:31)<br> 
		&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:47797:5)<br> 
		&nbsp; &nbsp;at trim_prefix (/lc/index.js:47371:13)<br> 
		&nbsp; &nbsp;at /lc/index.js:47340:7<br> 
		&nbsp; &nbsp;at Function.process_params (/lc/index.js:47391:12)<br> 
		&nbsp; &nbsp;at next (/lc/index.js:47331:10)<br> 
		&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:47793:12)<br> 
		&nbsp; &nbsp;at trim_prefix (/lc/index.js:47371:13)<br> 
		&nbsp; &nbsp;at /lc/index.js:47340:7<br> 
	    &nbsp; &nbsp;at Function.process_params (/lc/index.js:47391:12)
	</pre>\n</body>\n
</html>\n"
```

InternalServerError: 
**Transaction gas price supplied is too low**
**There is another transaction with same nonce in the queue**
**Try increasing the gas price or incrementing the nonce.**

`from: 1, to: 2, total_deposit: 1_000_000_000_000_000_000`

```
scenario:
  serial:
    tasks:
      - parallel:
          name: "Open 15 channels in both directions"
          tasks:
            - open_channel: {from: 0, to: 1, total_deposit: 1_000_000_000_000_000_000}
            - open_channel: {from: 1, to: 0, total_deposit: 1_000_000_000_000_000_000}
**fails**   - open_channel: {from: 1, to: 2, total_deposit: 1_000_000_000_000_000_000}
            - open_channel: {from: 2, to: 1, total_deposit: 1_000_000_000_000_000_000}
```

node 1: **0xb391499f911c274E5bE4aA91ce5e8E187aBE98b2**
node 2: **0x5dB2268C8F2Eca821071Cc82f9c0B5b11B47db6c**

[scenario-player-run_bf7_long_path_2020-11-05T02:05:58.log](https://github.com/raiden-network/light-client/files/5492623/scenario-player-run_bf7_long_path_2020-11-05T02.05.58.log)

Node1 Node2 logs
[bf7_node1_node2_05Nov2020.tar.gz](https://github.com/raiden-network/light-client/files/5492625/bf7_node1_node2_05Nov2020.tar.gz)
